name: GraalVM Native Image

on:
  push:
    tags:
    - '*'
    paths-ignore:
      - LICENSE
      - '*.md'

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

env:
  releaseBuild: ${{ github.event_name == 'push' && contains(github.ref, 'refs/tags/') }}

jobs:
  native-build:
    name: GraalVM latest ${{ matrix.java-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        version: [ '20.0.1' ]
        java-version: [ '20.0.1' ]
        os: [ macos-latest, windows-latest ]

    outputs:
      version: ${{ github.ref_name }}

    steps:
      - name: 🛎️ Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: ☕ Setup GraalVM Build
        uses: graalvm/setup-graalvm@v1
        with:
          version: ${{ matrix.version }}
          java-version: ${{ matrix.java-version }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          distribution: 'graalvm'
          cache: 'gradle'
          set-java-home: 'true'
          native-image-job-reports: 'true'

      - name: 🏗️ Native Image Build & Test
        id: native-build
        run: |
          ./gradlew nativeCompile
          ls -ltrh hildr-node/build/native/nativeCompile/hildr-node

      - name: 📤 Upload ${{ matrix.os }} native image
        uses: actions/upload-artifact@v3
        with:
          name: hildr-node-${{ matrix.os }}
          path: |
            hildr-node/build/native/nativeCompile/hildr-node
          if-no-files-found: error

  native-build-linux:
    name: GraalVM latest ${{ matrix.java-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        version: [ '20.0.1' ]
        java-version: [ '20.0.1' ]
        os: [ ubuntu-latest ]

    outputs:
      version: ${{ github.ref_name }}

    steps:
      - name: 🛎️ Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: ☕ Setup GraalVM Build
        uses: graalvm/setup-graalvm@v1
        with:
          version: ${{ matrix.version }}
          java-version: ${{ matrix.java-version }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          distribution: 'graalvm'
          cache: 'gradle'
          set-java-home: 'true'
          native-image-job-reports: 'true'

      - name: 🏗️ Native Image Build & Test
        id: native-build
        run: |
          ./gradlew buildBinary
          ls -ltrh hildr-node/build/binary/hildr-node

      - name: 📤 Upload ${{ matrix.os }} native image
        uses: actions/upload-artifact@v3
        with:
          name: hildr-node-${{ matrix.os }}
          path: |
            hildr-node/build/binary/hildr-node
          if-no-files-found: error

  native-build-musl:
    name: GraalVM + musl static image
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: ☕ Setup GraalVM Build
        uses: graalvm/setup-graalvm@v1
        with:
          version: '20.0.1'
          java-version: '20.0.1'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'gradle'
          native-image-musl: 'true'
          set-java-home: 'true'
          native-image-job-reports: 'true'

      - name: 🏗️ Build static image with musl libc
        id: native-build
        run: |
          ./gradlew buildBinaryStatic
          ls -ltrh hildr-node/build/binary/hildr-node

      - name: 📤 Upload static binary
        uses: actions/upload-artifact@v3
        with:
          name: hildr-node
          path: |
            hildr-node/build/binary/hildr-node
          if-no-files-found: error

  release:
    name: 🚰 Release new version.
    needs: [ native-build, native-build-musl, native-build-linux ]
    if: startsWith(github.ref, 'refs/tags/') && needs.native-build.result == 'success'
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️Check out the source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: ⚙️Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: ".github/config/configuration.json"
          commitMode: true
          ignorePreReleases: ${{ !contains(github.ref, '-') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ⏬Download all the build artifacts
        uses: actions/download-artifact@v3
        with:
          path: release-artifacts

      - name: ✨Github Release (version = ${{ needs.native-build.outputs.version }})
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.github_release.outputs.changelog }}
          files: |
            ${{ github.workspace }}/release-artifacts/**
          generate_release_notes: true
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}